### ISSUE TITLE
io/console not required by default

### ISSUE THREAD

**Issue by jannisch** [piotrmurach/tty-prompt#20]
Hello,
I use a simple application with `TTY::Prompt.ask` and `TTY::Prompt.select` but since a few weeks ago I experience an issue that `IO#echo=` is called by tty-prompt but not required (imported) before.

[This](http://ruby-doc.org/core-2.3.1/IO.html#class-IO-label-io-2Fconsole) Ruby API page tells that the method is part of `io/console` and manually requiring this file actually fixes the issue.

Here is the full stack trace:
```
 /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/reader/mode.rb:24:in `ensure in echo': undefined method `echo=' for #<IO:<STDIN>> (NoMethodError)
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/reader/mode.rb:24:in `echo'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/reader.rb:119:in `block in read_line'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/reader.rb:60:in `buffer'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/reader.rb:118:in `read_line'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/question.rb:151:in `read_input'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/question.rb:134:in `process_input'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/question.rb:105:in `render'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt/question.rb:96:in `call'
	from /usr/lib/ruby/gems/2.3.0/gems/tty-prompt-0.7.0/lib/tty/prompt.rb:103:in `ask'
```

**Comment by piotrmurach** [comment]
Thanks a ton for reporting this. Released patch `v0.7.1` that should fix this.
